version: '3'
services:
  nginx:
    build: .
    container_name: nginx-static_nginx
    restart: always
    # See: https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/#tuning-the-operating-system
    # should be similar to server backlog from nginx.conf
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - "./config/nginx.conf:/etc/nginx/nginx.conf"
      - "./log:/var/log/nginx"
      - "./www:/www/data"
    ports:
      - "80:80"
      - "443:443"
