{
 "title": "HttpCmp Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": "label_values(env)" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(http_requests_seconds{env=\"$env\"}, service)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(http_requests_seconds{service=\"$service\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS per status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Opened file descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (process_files_open_files{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
     "legendFormat": "opened",
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
    },
    {
     "expr": "sum (process_files_max_files{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Requests in the system",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(http_requests_calls_incoming_total{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m])) - sum (rate(http_requests_calls_total{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "RPS 5xx per endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\",status=~\"5..\"}[1m]))",
     "legendFormat": "{{handler}}",
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
    }
   ]
  },
  {
   "title": "RPS 5xx per endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\",status=~\"5..\"}[1m]))",
     "legendFormat": "{{handler}}",
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response time per percentile",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (quantile) (rate(http_requests_seconds{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{quantile}}"
      },
      {
       "expr": "sum(rate(http_requests_seconds_max{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Response time (p99) per endpoint",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max by (route) (http_requests_seconds{env=\"$env\",service=\"$service\",instance=\"$instance\",quantile=\"0.999\"})",
       "legendFormat": "{{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Client RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (client) (rate(http_clients_calls_total{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{client}}",
       "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
      }
     ]
    },
    {
     "title": "HTTP Client RPS per status code",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (status) (rate(http_clients_responses_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{status}}",
       "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
      }
     ]
    },
    {
     "title": "HTTP Client Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
     "yaxes": [
      { "format": "clocks" }
     ],
     "targets": [
      {
       "expr": "max by (client) (http_clients_responses_seconds{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{client}}",
       "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
      }
     ]
    },
    {
     "title": "HTTP Client Connections usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (client) (http_clients_connections{env=\"$env\",service=\"$service\",instance=\"$instance\"}) / sum by (client) (http_clients_connections_capacity{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{client}}"
      }
     ]
    },
    {
     "title": "HTTP Client Connections pending requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (client) (http_clients_connections_pending_requests{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{client}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Repositories RPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (repository, repositoryMethod) (rate(repositories_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{repository}}.{{repositoryMethod}}",
       "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
      }
     ]
    },
    {
     "title": "Repositories Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (repository, repositoryMethod) (repositories_seconds{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{repository}}.{{repositoryMethod}}",
       "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(system_cpu_count{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "process_cpu_usage{env=\"$env\",service=\"$service\",instance=\"$instance\"} * system_cpu_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Container CPU usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(system_cpu_count{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "max"
      },
      {
       "expr": "system_cpu_usage{env=\"$env\",service=\"$service\",instance=\"$instance\"} * system_cpu_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max MEM (heap) usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max(sum by (area) (jvm_memory_max_bytes{env=\"$env\",service=\"$service\",instance=\"$instance\",area=\"heap\"}))",
       "legendFormat": "max"
      },
      {
       "expr": "max(sum by (area) (jvm_memory_committed_bytes{env=\"$env\",service=\"$service\",instance=\"$instance\",area=\"heap\"}))",
       "legendFormat": "comitted"
      },
      {
       "expr": "max(sum by (area) (jvm_memory_used_bytes{env=\"$env\",service=\"$service\",instance=\"$instance\",area=\"heap\"}))",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "MEM (heap) usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by (area) (jvm_memory_used_bytes{env=\"$env\",service=\"$service\",instance=\"$instance\",area=\"heap\"}) / sum by (area) (jvm_memory_max_bytes{env=\"$env\",service=\"$service\",instance=\"$instance\",area=\"heap\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Old Gen Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_usage_after_gc_percent{env=\"$env\",service=\"$service\",instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC pause time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (jvm_gc_pause_seconds_max{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC pause count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 71 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (instance) (rate(jvm_gc_pause_seconds_count{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "GC CPU overhead",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 71 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_overhead_percent{env=\"$env\",service=\"$service\",instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Live threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by(instance) (jvm_threads_live_threads{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "live"
      },
      {
       "expr": "sum by(instance) (jvm_threads_daemon_threads{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "daemon"
      }
     ]
    },
    {
     "title": "Threads per state",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max by (state) (jvm_threads_states_threads{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs per level",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum by (level) (rate(logback_events_total{env=\"$env\",service=\"$service\",instance=\"$instance\"}[1m]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Loaded classes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max(jvm_classes_loaded_classes{env=\"$env\",service=\"$service\",instance=\"$instance\"})",
       "legendFormat": "loaded"
      }
     ]
    }
   ]
  }
 ]
}