version: "3.8"
services:
  prometheus:
    build: prometheus/
    user: root
    container_name: metrics-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9990:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - metricsnet
    extra_hosts:
      - host.docker.internal:172.17.0.1
  grafana:
    build: grafana/
    container_name: metrics-prometheus-grafana
    depends_on:
      - prometheus
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    links:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3003:3000"
    networks:
      - metricsnet
networks:
  metricsnet:
    driver: bridge
volumes:
  grafana-data:
