apiVersion: 1

deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:80
    isDefault: true
    editable: true
    jsonData:
      graphiteVersion: "1.1.x"
