{
 "title": "HTTPCMP Service",
 "tags": [ "httpcmp" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "prefix", "query": "stats.httpcmp" },
   { "name": "service", "label": "Service", "query": "$prefix.*" },
   { "name": "instance", "label": "Instance", "query": "$prefix.$service.*" }
  ]
 },
 "panels": [
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RPS per status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.*.m1_rate, 'sum', 8)"
    }
   ]
  },
  {
   "title": "RPS 5xx per endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.5*.m1_rate, 'sum', 6)"
    }
   ]
  },
  {
   "title": "RPS per endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.*.m1_rate, 'sum', 6)"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Response time per percentile",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.*.{max,p99,p75,p50}, 'max', 9)"
    }
   ]
  },
  {
   "title": "Response time p99 per endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.api.*.*.*.*.p99, 'sum', 6)"
    }
   ]
  },
  { "title": "HTTP Clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "HTTP Client RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.http-clients.*.calls.m1_rate, 'sum', 5)"
    }
   ]
  },
  {
   "title": "HTTP Client RPS per status code",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.http-clients.*.time-to-first-byte.*.*.m1_rate, 'sum', 5, 8)"
    }
   ]
  },
  {
   "title": "HTTP Client time to first byte",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.http-clients.*.time-to-first-byte.*.*.p99, 'max', 5)"
    }
   ]
  },
  {
   "title": "HTTP Client Connection usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.http-clients.*.connections.utilization, 'max', 5)"
    }
   ]
  },
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Repositories RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.repositories.*.*.m1_rate, 'sum', 5, 6)"
    }
   ]
  },
  {
   "title": "Repositories p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "groupByNodes($prefix.$service.$instance.repositories.*.*.p99, 'max', 5, 6)"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries($prefix.$service.$instance.process.cpu.max), 'max')"
      },
      {
       "target": "groupByNodes($prefix.$service.$instance.process.cpu.used, 'max', 3)"
      }
     ]
    },
    {
     "title": "Container CPU usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries($prefix.$service.$instance.system.cpu.max), 'max')"
      },
      {
       "target": "groupByNodes($prefix.$service.$instance.system.cpu.used, 'max', 3)"
      }
     ]
    },
    {
     "title": "Container Memory usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries($prefix.$service.$instance.system.mem.max), 'max')"
      },
      {
       "target": "groupByNodes($prefix.$service.$instance.system.mem.used, 'max', 3)"
      }
     ]
    },
    {
     "title": "Container File Descriptors usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "alias(maxSeries($prefix.$service.$instance.system.descriptors.max), 'max')"
      },
      {
       "target": "groupByNodes($prefix.$service.$instance.system.descriptors.used, 'max', 3)"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max time in GC",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.gc.*.time, 'max', 6)"
      }
     ]
    },
    {
     "title": "Max GC Collections per 10min",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasSub(summarize(derivative(groupByNodes($prefix.$service.$instance.jvm.gc.*.count, 'max', 6)), '10minutes'), '^.*derivative\\(([^)]+)\\).*$', '\\1')"
      }
     ]
    },
    {
     "title": "Heap usage per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.memory.heap.usage, 'max', 3)"
      }
     ]
    },
    {
     "title": "Max heap usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.memory.heap.{init,max,used,committed}, 'max', 7)"
      }
     ]
    },
    {
     "title": "Live threads per host",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.threads.live, 'max', 3)"
      }
     ]
    },
    {
     "title": "Threads per state (max)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.threads.states.*, 'max', 7)"
      }
     ]
    },
    {
     "title": "Max loaded classes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.jvm.classes.*, 'max', 6)"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Logs per second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.logback.events.level.*.m1_rate, 'sum', 4)"
      }
     ]
    },
    {
     "title": "Logs per level",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "target": "groupByNodes($prefix.$service.$instance.logback.events.level.*.m1_rate, 'sum', 7)"
      }
     ]
    }
   ]
  }
 ]
}