version: "3"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      # root username is 'root'
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    ports:
      - 8836:8080
