# https://github.com/elastic/elasticsearch-docker
FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.6

# Add your elasticsearch plugins setup here
RUN elasticsearch-plugin install \
  pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:6.8.6
